### PR TITLE
Add Card / Cards Plugin

### PR DESCRIPTION
**Pull request by wad3g**
### Card / Cards Container Plugin

Added basic flexbox card and cards container with the bare essentials ([#46](https://github.com/KingPixil/wing/issues/46)).

*Note:* Only differences between the barebones card and the card(s) using Wing's utility classes are:

* Card Header text is centered
* Card Body is centered via `.center` - the flexbox utility class

#### Card (barebones, no utility classes)
```
      <div class="card">
        <div class="card-header">
          Card Header
        </div>
        <div class="card-body">
          T_his is a card body.
        </div>
        <div class="card-footer">
          Card Footer
        </div>
      </div>
```
cards

#### Cards w/ Wing utility classes
```
    <div class="cards">
      <div class="card">
        <div class="card-header text-center">
          Card Header
        </div>
        <div class="card-body center">
          This is a card body.
        </div>
        <div class="card-footer">
          Card Footer
        </div>
      </div>
      <div class="card">
        <div class="card-header text-center">
          Card Header
        </div>
        <div class="card-body center">
          This is a card body.
        </div>
        <div class="card-footer">
          Card Footer
        </div>
      </div>
      <div class="card">
        <div class="card-header text-center">
          Card Header
        </div>
        <div class="card-body center">
          This is a card body.
        </div>
        <div class="card-footer">
          Card Footer
        </div>
      </div>
      <div class="card">
        <div class="card-header text-center">
          Card Header
        </div>
        <div class="card-body center">
          This is a card body.
        </div>
        <div class="card-footer">
          Card Footer
        </div>
      </div>
      <div class="card">
        <div class="card-header text-center">
          Card Header
        </div>
        <div class="card-body center">
          This is a card body.
        </div>
        <div class="card-footer">
          Card Footer
        </div>
      </div>
    </div>
```

cards-w-utilities

### CODE REVIEW

**Comment by KingPixil** [comment]
Looking good! There are some conflicts, so could you update the PR with a `git pull` and a fresh build?

Also, I have some suggestions:

* Why have a `.cards` class? I think a card should just be a component that can be added anywhere, instead of having them always be in a collection
  * They are also right next to each other, I think a better way would just be utilizing the grid
* Instead of specifically styling buttons to have no margins, we can have items be fit to stretch across the footer, by adding `align-items: stretch`

**Comment by wad3g** [comment]
The cards class is only there if you're​ using more than one card (see the top card in the GIF's).

They don't have to be right next to one another, maybe we need to add additional spacing utilities so it's consistent across the entirety of the framework and didn't vary from plugin to plugin.

I personally prefer flexbox over using a grid for these cards. The markup is cleaner, the card doesn't care whether one had more content than the other - it'll still be equal heights. You use less media queries, classes, and have more control over what/how you want things to function and look.  

This eliminates the need for `display: table`, additional markup associated with a grid, or potentially having to you `position: absolute` for vertically centering content.

It's your call though so let me know your thoughts.

**Comment by KingPixil** [comment]
Cool, just wanted to see the thoughts behind it. I still think there should be some more spacing between the cards.

Still, I think you should add `align-items:stretch` to the footer and header, and remove the special style for buttons within the footer. Along with that, remove some styles such as `text-align: center`, allowing for left/right aligned elements as well.

Here is a simple demo of styles for cards I made, let me know what you think: https://jsfiddle.net/s56e4jod/

**Comment by wad3g** [comment]
@KingPixil I do like your fiddle. So are you going for material-esque design patterns?

I decided to do a bit of a mashup between your fiddle and my version. I know you were just throwing an example together, but your example does prevent us from being able to use some utility classes.

I dropped mine in a S3 bucket. Let me know what you think:

http://wad3g.s3-website.us-east-2.amazonaws.com/

**Comment by KingPixil** [comment]
Yeah, something like material at least, but it is definitely not a material design CSS framework.

Looks good! I do think the hover effect should be added by the user instead of the framework. Also, what utility classes does my solution not work with? I'm curious to know 😛 

Nonetheless, it looks good! We're almost ready for Wing v1.0.0!

**Comment by wad3g** [comment]
@KingPixil Do I have hover classes on?  Oops.

The only utility class (of the two I've used `.text-center` / `.center`) was `.text-center` on `.card-header`, but that's because of the padding on that class.

I think I should probably go ahead and add `.text-left` and `.text-right`  to the utility classes. Only makes sense, no?

**Comment by wad3g** [comment]
@KingPixil, not sure what these withstanding issues are. Do the check need to be rerun?

**Comment by KingPixil** [comment]
The CodeFactor check is fine, but there are some conflicts in `wing.min.css`

**Comment by wad3g** [comment]
@KingPixil Wow, no idea what the hell happened there but it should be good to go now.

**Comment by KingPixil** [comment]
Thanks! 👍

**Comment by KingPixil** [comment]
Not sure how I overlooked this, but the `nav.css` file was cleared... I'm just going to restore it

**Pull request merged**
