### PR TITLE
Remove `overflow: hidden` from `.cards`

### PR DESCRIPTION
**Pull request by peduarte**
Fixes https://github.com/KingPixil/wing/issues/56

### CODE REVIEW

**Comment by peduarte** [comment]
wow, what's happened to this PR?

**Comment by KingPixil** [comment]
Odd, I haven't done anything to it. Try making a new PR from a fresh clone of the repo. I'll merge later (I am on mobile).

**Comment by peduarte** [comment]
@KingPixil No worries!

**Comment by KingPixil** [comment]
Any updates on this?

**Pull request closed without merging**
