### PR TITLE
Feature: improve gulpfile

### PR DESCRIPTION
**Pull request by marcobiedermann**
Hi @KingPixil 

I've cleaned up and improved your gulpfile a bit. Here is a short breakdown of it:
* Use ES2015 syntax (`const`, `import`, `arrow functions`, `template strings`)
* Use ES2015 template strings for banner to make it more readable
* Remove unused devDependencies
* Add Sourcemaps to help with debugging
* Replace deprecated `gulp-minify-css` with `gulp-clean-css`
* Compile CSS files to update URL to `http://usewing.ml/`
* Add gulp task for development `gulp` / `npm run start` and production `gulp build` / `npm run build`
* Remove global dependencies / CLI tools
* Update Travic-CI task

If you got any further questions, feel free to hit me up 😄  🎉

### CODE REVIEW

**Comment by KingPixil** [comment]
Hey @marcobiedermann!

Thank you so much for all of your hard work! I agree that the gulpfile was *very* messy, and needed some cleaning.

Why use Babel? Maybe just keep it at ES2015?

**Comment by marcobiedermann** [comment]
@KingPixil You are very welcome.
Unfortunately Node v6 does not support "import".
If you like to use it, you have to use a Babel.js preset ("babel-preset-es2015").
The only way around this dependency is to use the AMD module require method (const module = require("module").
I personaly prefer to use the new syntax and drop "babel" as soon as it is supported by Node natively.

**Comment by KingPixil** [comment]
Hey @marcobiedermann, thanks for the response. What are the advantages of using `import`?

**Comment by marcobiedermann** [comment]
@KingPixil 
Disadvantages of `import`;
* Currently you need a transpiler like `Babel.js` because it is not natively supported.

Advantages of `import`:
* You could use destructuring syntax to only import what you need `import { version } from './package.json'`;
* You could use aliases `import { jQuery as $ } from 'jquery'`
* It is the new syntax, get used to it

I personally think to use the new syntax early and take advantage of it. Use a transpiler to shim older environments and drop it as soon as it is supported.

**Comment by KingPixil** [comment]
Sorry, I don't want to introduce new dependencies into Wing, it's simply a CSS framework 😄

**Pull request closed without merging**
