### PR TITLE
V1.0.0 beta: tables, image helper classes & small improvments

### PR DESCRIPTION
**Pull request by CodeBrauer**
I will work on this pull request today & tomorrow, but you can have a look and maybe review it a bit.

###  Remove `@import`

```css
@import url(https://fonts.googleapis.com/css?family=Quicksand);
@import url(https://fonts.googleapis.com/css?family=Open+Sans);
```

This 2 requests will block parallel downloads. That means the loading time can be very slowly.

Recommendation: Use a single `<link>`:

```html
<link href="//fonts.googleapis.com/css?family=Quicksand|Open+Sans" rel="stylesheet" type="text/css">
```

Read more about this here: https://github.com/CSSLint/csslint/wiki/Disallow-@import

### Tables

I've added basic tables support (#28).

If somebody don't wants to have table styled the way wing does, it requires a class for the styles.

Basic style is just `.table`. There are more features than can be just enabled by adding the classes:

- ~~`.striped`: will add a grey background to every second row~~
- ~~`.hover`: will highlight current row on hover~~
- `.responsive`: will flip the whole table, so it's mobile friendly. Look a demo here:

gif responsive table demo

### Image helper classes

- `.img-circle`: img as a circle
- `.img-rounded`: img with border radius of 3px (like the buttons)
- `.img-fluid`: responsive image

### responsive helpers

- `.hide-phone`
- `.hide-tablet`

### CODE REVIEW

**Comment by KingPixil** [comment]
Hey! 

Looks great! The table looks cool, but maybe remove the extra things, such as .striped and .hover, I think the user should be able to add it themselves. (Remember, Wing must be as minimal as possible :wink:)

Also, you are editing the dist file, please make a new file in src, like `table.css`, and edit the gulpfile, let me know if you need help with this.

Also, if you haven't noticed, Wing v1 will only require Open Sans, no more Quicksand. I am aware of the loading issues, and it seems like a good decision to remove @import, and add the link's in the documentation.

**Comment by CodeBrauer** [comment]
I've added an src/tables.css and edited in https://github.com/KingPixil/wing/pull/37/commits/a20dda5fe85114a01837f16d6b94821dfcd3788d

Yes, the "special" classes things can be removed. I should keep this minimal

**Comment by CodeBrauer** [comment]
So, I think my PR is ready to go, please review it. I've just adjusted my codestyle so it matches yours 😉

**Comment by KingPixil** [comment]
Looks super great, thanks!

**Pull request merged**
