### PR TITLE
Fixing height of outlined button (fixes #33)

### LINKED ISSUE #33: Outlined buttons have different height
If you use both buttons side by side they don't align perfect, because the outlined buttons has +6px of height.

bildschirmfoto 2016-10-27 um 12 21 33
bildschirmfoto 2016-10-27 um 12 21 19

### PR DESCRIPTION
**Pull request by CodeBrauer**
#33

### CODE REVIEW

**Comment by KingPixil** [comment]
Hey @CodeBrauer, super sorry for this late response.

I think it would be better to take out padding on the outlined buttons, as I think that is the issue. For example, instead of `12px 12px`, the padding should be `9px 9px`.

**Comment by CodeBrauer** [comment]
Hey there, yes using padding would be the cleaner way. I fixed it now.

**Comment by CodeBrauer** [comment]
Any updates?

**Comment by KingPixil** [comment]
Whoops! Forgot about it! Thank you for the fix 👍

**Pull request merged**
